[build-system]
requires = [
    "setuptools>45",
    "setuptools_scm>=6.2",
    "wheel"
]

build-backend = "setuptools.build_meta"

[tool.setuptools_scm]

[tool.coverage.run]
source = ["gbpcli"]
omit = ["src/gbpcli/__main__.py"]
